# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RunUser',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('long', models.DecimalField(decimal_places=3, default=0, max_digits=7)),
                ('online', models.BooleanField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('opponent_name', models.CharField(default='', max_length=30)),
                ('opponent_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
    ]
