# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacku', '0003_runuser_random_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runuser',
            name='opponent_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='runuser',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
